name: testing with codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: testing with codecov
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov
      run: |
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      
# name: tests
# on: [push]
# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v3


#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v3
#         with:
#           python-version: '3.11'
# #           architecture: 'x64'
#       - run: pip install poetry==1.3.1
#       - run: pip install nox==2023.4.22
#       - run: nox -rs black_check flake8 mypy tests

# name: Use Codecov
# on:
#   workflow_dispatch:
  
# jobs:
#   launch: # my name
#     name: Launch Codecov
#     runs-on: ubuntu-latest
#     steps:
#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v3
